### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by iquasere** [satackey/action-google-drive#15]
The troubleshooting needs to be updated, I did everything as detailed in japanese, and got this:
![image](https://user-images.githubusercontent.com/16226371/110487823-dab39380-80e5-11eb-8dbd-19d9bddc8610.png)
It is one step further from the app being blocked, it still is not working as needed.

**Comment by ayutaz** [comment]
Hello.
I had the same situation and was able to solve the problem by adding a user to the test user in the OAuth consent screen of Google Cloud Platform.
![image](https://user-images.githubusercontent.com/41669061/114876924-c3309e80-9e39-11eb-80d0-4df9f7803718.png)
The screen is in Japanese, but don't worry about it.

**Comment by iquasere** [comment]
Yes, this fixes it ^^
